name: Deploy Image to GHCR

env:
  DOTNET_VERSION: '7.0.x'

on:
  pull_request:
    branches:
      - master

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            env:
              CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
              CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
              CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
            run: |
              docker build --build-arg CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME \
                --build-arg CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
                --build-arg CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
                --tag ghcr.io/karimdevwm/karim_eshop_api:latest .
              docker push ghcr.io/karimdevwm/karim_eshop_api:latest